configuration:
    authenticationConfiguration:
        password: "rambo"
    serverConfiguration:
        # type can be OPEN_URL or FORCED_URL or FORCED_URL_NO_PASSWORD - later two need proxiedUrl uncommented
        type: "FORCED_URL_NO_PASSWORD"
        listenHost: "localhost"
        port: "8008"
        requestsPerConnection: "10000"
        proxiedUrl: "wss://open.senrigan.io/ws/async/writeup/text_generation/session/1333334/"
    transportConfiguration:
        sendPrefix: "" # these allow a prefix and suffix on all arbitrary requests to proxied server
        sendSuffix: ""
